### ISSUE TITLE
Multiple gem servers

### ISSUE THREAD

**Issue by smellsblue** [bundler/gemstash#2]
We use multiple gem sources in a single gemfile. It would be nice to point to gemstash and it will pull from all of them.

**Comment by pcarranza** [comment]
:+1: 

> I think that it is by definition a priority based linear system, that is, as you said, try the first, if it’s not there, try the second, and so on
> also think that we should have as many storage folders as upstream servers
> so, we should first go through all the storage, and if we don’t find it, then we should cache it back
> simply:
> storages.each { return gem if i_have_this_gem }
> upstream_servers.each { cache_and_return if it_has_this_gem }
> both storages and upstream servers are priority based lists, and the upstream knows which storage to use to do the caching, probably because we need to build the “http client” for the caching itself

So, we just to define our upstream servers in order of priority (most important first) and then we can just figure out the caching and fetching strategy from there.

**Comment by indirect** [comment]
This is a good idea! Rather than putting the cache for every server in one place, let's separate caches on a per-server basis. Bundler was originally built with multiple servers and "order of priority", and it turned out so terribly that we had to issue a CVE: http://bundler.io/blog/2014/08/14/bundler-may-install-gems-from-a-different-source-than-expected-cve-2013-0334.html

I think a way to make this work that is straightforward is to add a configuration file that allows mapping gemstash URLs to specific servers. For example:

```yaml
# config.yml
gem_servers:
  gemfury: https://gemfury.io
```

Then, `source "https://gemstash.local/gemfury"` or `bundle config mirror.https://gemfury.io https://gemstash.local/gemfury` ensures that gemstash can be used as a passthrough cache for the Gemfury source.

**Comment by smellsblue** [comment]
@indirect I like that! So would that source then only bundle against the gemfury upstream?

One thing I would like in a Gemfile we use is to have the gemstash server deal with all upstreams for us. We ran into some strange issues with bundler when trying to bundle against a couple of upstreams... we got some gem not found errors that we didn't expect and had to hack around it to get the gems (heh, probably should have opened a ticket on that, sorry!).

After reading the CVE, it looks like a priority system is a bad idea, and it should instead error out if you try to get a gem that exists on multiple upstreams. Maybe something like this:

```
# config.yml
gem_servers:
  gemfury: https://gemfury.io
  rubygems: https://www.rubygems.org
```

Then, if you try to make an api call against gemstash and the gem exists on multiple of the upstreams (if you use `https://gemstash.local` rather than a scoped upstream like `https://gemstash.local/gemfury`), it will error out, and to resolve it you must either append something on the url like `https://gemstash.local?rubygems=rake,rack&gemfury=sinatra` or add configuration like:

```
# config.yml
gem_servers:
  gemfury: https://gemfury.io
  rubygems: https://www.rubygems.org
gem_resolutions:
  rubygems:
  - rake
  - rack
  gemfury:
  - sinatra
```

I presume we must have the gem fully hosted from one upstream too... so if I have some versions of rack on 2 different upstreams, it can only ever install rack from one of the upstreams, so it would be an error regardless of if the version needed is hosted on one and not the other (otherwise that seems like it would be a security vulnerability).

There's a weird scenario though... what if I install rack when only 1 upstream has the gem, then I bundle on a new machine... but at this point, another upstream has rack. Should gemstash be calling out to the various upstreams and see if it exists on more than one upstream? I'm thinking, once it is cached, it should just fetch from there with no web calls, and it seems like a reasonable and secure way of doing it... then when I bundle update, I would get the error about multiple sources for the gem.

Thoughts?

**Comment by pcarranza** [comment]
I really like the idea of multiple endpoints and explicit resolutions for specific gems. 

I'm guessing that the main use case for multiple upstream servers is having the ability to mix those servers for different purposes, for ex: using the pro version of sidekiq, which is provided with a gem server for that specific gem.

Is this a valid use case for multiple upstream servers?

If so, having the mapping for specific gems makes a lot of sense. This mapping configurations could also be provided by whoever is serving this to simplify the setup. We could even handle auth tokens in the same configuration file with this approach. Maybe something like:

```
# config.yml
upstream-servers:
  gemfury:
    url: https://gemfury.io
    auth-token: xxxxx
    gems:
      - sinatra
  rubygems: 
    url: https://www.rubygems.org
    gems:
      - rake
      - rack
    default-upstream: true
  sidekiq:
    url: https://sidekiq.org
    auth-token: yyyyy
    gems:
      - sidekiq
```

With this we could support mirroring an upstream server to a specific path, as you propose @indirect, also we could set up mixed servers in the default endpoint for specific gems.

Regarding having the gem cached, I think we should just serve it without making any further calls. The upstream servers should only be used to fetch those gems initially, but once they are cached, they should be served from the local storage.

This also matches in behavior with the idea of privately hosted gems: if we have the gem, we just serve it.

Regarding having multiple upstream sources for the same gem, is there a way of getting a hash of the gem (etags maybe?) to check if they are the same? 
This could be a simple way of resolving the conflict: request the header of all the upstreams that have the gem, and compare the etags, if we find a difference  we could only trust the authoritative source (rubygems) or force this conflict resolution into the user. Finally, on download, check the hash just to be sure.
